requirements:
    - requirement:
        name: "Req1"
        nodes:
            - ["INIT", "INSTANTIATE"]
            - ["A", "a"]
            - ["END", "TERMINATE"]
        root: "INIT"
        edges:
            - ["INIT", ["A"]]
            - ["A", ["END"]]

